// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {api} from '../models';

export function ApproveDecision(arg1:string,arg2:string):Promise<db.DecisionItem>;

export function GetAPIURL():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetDecision(arg1:string):Promise<db.DecisionItem>;

export function IssueKey(arg1:string):Promise<api.IssueKeyResult>;

export function ListDecisions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<api.ListDecisionsResult>;

export function ListKeys():Promise<Array<db.AgentKey>>;

export function Quit():Promise<void>;

export function RejectDecision(arg1:string,arg2:string):Promise<db.DecisionItem>;

export function RevokeKey(arg1:string):Promise<void>;

export function Stats():Promise<api.StatsResult>;
