// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveDecision(arg1, arg2) {
  return window['go']['main']['App']['ApproveDecision'](arg1, arg2);
}

export function GetAPIURL() {
  return window['go']['main']['App']['GetAPIURL']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDecision(arg1) {
  return window['go']['main']['App']['GetDecision'](arg1);
}

export function IssueKey(arg1) {
  return window['go']['main']['App']['IssueKey'](arg1);
}

export function ListDecisions(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ListDecisions'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RejectDecision(arg1, arg2) {
  return window['go']['main']['App']['RejectDecision'](arg1, arg2);
}

export function RevokeKey(arg1) {
  return window['go']['main']['App']['RevokeKey'](arg1);
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}
